name: Course Reminder

on:
  schedule:
    # 早上7:40运行（UTC时间23:40，对应北京时间7:40）- 上午课程提醒
    - cron: '40 23 * * *'
    # 中午13:10运行（UTC时间5:10，对应北京时间13:10）- 下午课程提醒
    - cron: '10 5 * * *'
    # 晚上21:00运行（UTC时间13:00，对应北京时间21:00）- 每日课程总结
    - cron: '0 13 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run course reminder
      run: |
        python course_reminder.py
